[global]
developmentMode = false

[server]
headless = false
runOnSave = false
port = 8501
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = true

[runner]
magicEnabled = true
postScriptGC = true
fastReruns = true
enforceSerializableSessionState = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"